R/home.txt
The first book on the front page about space I think - plenty about temporal data but little on space, until now!
=> Add geocomputation with R

R/staging.txt
Added [twinetbook.john-coene.com/](https://twinetbook.john-coene.com/)
=> added twinetverse

R/exclude.txt, R/staging.txt
instead of https://github.com/rstudio/bookdown.org/pull/25
:)
=> add "Advanced R Solutions" to bookdown.org

R/staging.txt
=> Propose Hands-On Programming with R

R/staging.txt
A first draft of my new textbook Lightweight Machine Learning Classics with R is now available at https://lmlcr.gagolewski.com/
Could this be listed at bookdown.org? Thanks!!!
About. Explore some of the most fundamental algorithms which have stood the test of time and provide the basis for innovative solutions in data-driven AI. Learn how to use the R language for implementing various stages of data processing and modelling activities. Appreciate mathematics as the universal language for formalising data-intense problems and communicating their solutions. The book is for you if you're yet to be fluent with university-level linear algebra, calculus and probability theory or you've forgotten all the maths you've ever learned, and are seeking a gentle, yet thorough, introduction to the …
=> Lightweight Machine Learning Classics with R

R/staging.txt
Hello! I wrote a book with bookdown and would like it published in the archive. I tried following the instructions at https://bookdown.org/home/about/--I chose the "edit staging.txt" method. 
Please let me know if I need to do anything else! Thank you!
=> New Book - Schnitman-ASPR

R/staging.txt
We just love bookdown and wrote our new data science book using it. It will be published soon and we would love to add it to the bookdown website.
=> Adding new book to bookdown website

R/home.txt
@ColinFay asked me if this book can be promote to home page as it will be published soon (in 2020) in the R Series by Chapman & Hall. 
Can we do that ?
=> add engineering shiny to home page

.travis.yml
This should do the trick. 
I tested on my fork. It will on run the following steps in `script` only if `staging;txt` is in the modified files in a PR
Will see if that correctly runs :)
=> Exit travis if a PR is submitted without changes to Staging.txt

R/staging.txt
Add link to book: Behavior Analysis with Machine Learning and R
=> add book website

R/staging.txt
Just a course book found in a thread https://twitter.com/ceptional/status/1373772037030780931
=> Add psyc2016 course book

R/staging.txt
From https://twitter.com/ill_identified/status/1376019100485312512?s=11
=> Add translation of Rmarkdown Cookbook

R/staging.txt
don't know why it is not there
=> Add tidytextmining

R/staging.txt
Bookdown available at https://gorgens.github.io/compR-experimental/
=> Add Análise Experimental

R/staging.txt
To https://github.com/orchid00/actions_sandbox
=> action_sandbox book seems to have moved

R/staging.txt
This book uses the tufte style. Not sure if its info can be scraped successfully. Let's see.
=> add the book Data Analytics - A Small Data Approach

R/staging.txt
From https://twitter.com/epiRhandbook/status/1391728371948740610?s=20
=> add epirhandbook

R/staging.txt
https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/
=> add ISLR-tidymodels-labs

R/staging.txt
https://forwards.github.io/rdevguide
=> Add R developers guide

R/staging.txt
Creating an access port to BioViral bookdown, currently here 
(https://aimergdiaz.github.io/Bio-Virologia/)
=> Add Bio-Virologia

R/staging.txt
Learned from https://twitter.com/NathanTaback/status/1521504872650219523
=> Add the book "Design and Analysis of Experiments and Observational Studies using R"

R/staging.txt
The book tidy finance with R is built with bookdown and hosted on https://tidy-finance.org and is going to be printed by CRC Press end of 2022. Would be amazing to be listed on the homepage.
=> add the book tidy finance with R

R/external.txt
Seen in https://github.com/rstudio/bookdown.org/pull/215
=> mixomics changed url

R/staging.txt
Exploring Complex Survey Data Analysis Using R: A Tidy Introduction with {srvyr} and {survey}
=> Add Exploring Complex Survey Data Analysis Using R to bookdown

R/external.txt
Remove those books which are no more online
=> Unlist external books which are 404
